---

- name: Provision a {{ application_name }} web server
  hosts: mapstory
  sudo: yes
  sudo_user: root
  remote_user: vagrant
  vars:
    - update_apt_cache: yes
  vars_files:
    - host_vars/base.yml
    - host_vars/{{ env }}.yml

  roles:
    - common
    - web
    - celery