language: python

services:
  - elasticsearch

python:
  - "2.7"

env:
- DJANGO_SETTINGS_MODULE='mapstory.settings.test_settings'

virtualenv:
  system_site_packages: true

install:
  - cd ..
  - git clone https://github.com/MapStory/geonode.git
  - cd mapstory-geonode
  - sudo apt-get -qq -y update
  - sudo apt-get install -y libgdal1h python-gdal
  - sudo apt-get install -y python-virtualenv python-imaging python-lxml python-pyproj python-shapely python-nose python-httplib2 python-httplib2 gettext
  - sudo apt-get install -y --force-yes openjdk-6-jdk ant maven2 libjai-imageio-core-java --no-install-recommends
  - pip install -r requirements.txt

script:
  - python manage.py test

notifications:
  slack: mapstory:E2W57xKNNOKDDqRmtQHNUlBK
