#cp /home/jorge/Desktop/storyscapes/mapstory/importer/static/importer/partials/uploadWizard.html /home/jorge/Libraries/storyscapes/mapstory/importer/static/importer/partials/uploadWizard.html
cp /home/jorge/Desktop/storyscapes/mapstory/settings/base.py /home/jorge/Libraries/storyscapes/mapstory/settings/base.py
cp /home/jorge/Desktop/storyscapes/mapstory/static/mapstory/img/favicon.ico /home/jorge/Libraries/storyscapes/mapstory/static/mapstory/img/favicon.ico
cp /home/jorge/Desktop/storyscapes/mapstory/static/mapstory/img/mapstory-icon.png /home/jorge/Libraries/storyscapes/mapstory/static/mapstory/img/mapstory-icon.png
cp /home/jorge/Desktop/storyscapes/mapstory/templates/account/email/email_confirmation_subject.txt /home/jorge/Libraries/storyscapes/mapstory/templates/account/email/email_confirmation_subject.txt
cp /home/jorge/Desktop/storyscapes/mapstory/templates/account/email/invite_user.txt /home/jorge/Libraries/storyscapes/mapstory/templates/account/email/invite_user.txt
cp /home/jorge/Desktop/storyscapes/mapstory/templates/account/email/welcome_message.html /home/jorge/Libraries/storyscapes/mapstory/templates/account/email/welcome_message.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/account/email/welcome_message.txt /home/jorge/Libraries/storyscapes/mapstory/templates/account/email/welcome_message.txt
cp /home/jorge/Desktop/storyscapes/mapstory/templates/account/email/welcome_subject.txt /home/jorge/Libraries/storyscapes/mapstory/templates/account/email/welcome_subject.txt
cp /home/jorge/Desktop/storyscapes/mapstory/templates/base.html /home/jorge/Libraries/storyscapes/mapstory/templates/base.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/detail_base.html /home/jorge/Libraries/storyscapes/mapstory/templates/detail_base.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/fluent_comments/templatetags/threaded_list.html /home/jorge/Libraries/storyscapes/mapstory/templates/fluent_comments/templatetags/threaded_list.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/groups/organization_visit.html /home/jorge/Libraries/storyscapes/mapstory/templates/groups/organization_visit.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/index.html /home/jorge/Libraries/storyscapes/mapstory/templates/index.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/maps/_composer_body.html /home/jorge/Libraries/storyscapes/mapstory/templates/maps/_composer_body.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/maps/editor_tour.html /home/jorge/Libraries/storyscapes/mapstory/templates/maps/editor_tour.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/mapstory/_footer.html /home/jorge/Libraries/storyscapes/mapstory/templates/mapstory/_footer.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/mapstory/_header.html /home/jorge/Libraries/storyscapes/mapstory/templates/mapstory/_header.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/mapstory/_login_register.html /home/jorge/Libraries/storyscapes/mapstory/templates/mapstory/_login_register.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/mapstory/composer/load-map-dialog.html /home/jorge/Libraries/storyscapes/mapstory/templates/mapstory/composer/load-map-dialog.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/mapstory/composer/story-about-info.html /home/jorge/Libraries/storyscapes/mapstory/templates/mapstory/composer/story-about-info.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/mapstory/diary.html /home/jorge/Libraries/storyscapes/mapstory/templates/mapstory/diary.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/mapstory/donate.html /home/jorge/Libraries/storyscapes/mapstory/templates/mapstory/donate.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/people/_result_content.html /home/jorge/Libraries/storyscapes/mapstory/templates/people/_result_content.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/people/profile_detail.html /home/jorge/Libraries/storyscapes/mapstory/templates/people/profile_detail.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/provider/authorize.html /home/jorge/Libraries/storyscapes/mapstory/templates/provider/authorize.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/search/_result_content.html /home/jorge/Libraries/storyscapes/mapstory/templates/search/_result_content.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/search/_sort_filters_content.html /home/jorge/Libraries/storyscapes/mapstory/templates/search/_sort_filters_content.html
cp /home/jorge/Desktop/storyscapes/mapstory/templates/search/searchn.html /home/jorge/Libraries/storyscapes/mapstory/templates/search/searchn.html
